### ISSUE TITLE
ClassNotFoundException : org.apache.hadoop.conf.Configuration

### ISSUE THREAD

**Issue by ozzy-a1** [onefoursix/Cloudera-Impala-JDBC-Example#1]
Project builds OK, but fails with error below when attempting to run.

Missing some dependencies?
# 

Cloudera Impala JDBC Example
Using Connection URL: jdbc:hive2://hadoop_dev:21050/;auth=noSasl
Running Query: SELECT description FROM sample_07 limit 10
[WARNING] 
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
    at java.lang.Thread.run(Thread.java:695)
Caused by: java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
    at org.apache.hive.service.cli.thrift.EmbeddedThriftCLIService.<init>(EmbeddedThriftCLIService.java:32)
    at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:86)
    at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:104)
    at java.sql.DriverManager.getConnection(DriverManager.java:582)
    at java.sql.DriverManager.getConnection(DriverManager.java:207)
    at com.cloudera.example.ClouderaImpalaJdbcExample.main(ClouderaImpalaJdbcExample.java:37)
    ... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configuration
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 12 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.220 s
[INFO] Finished at: 2014-07-31T16:29:13-05:00
[INFO] Final Memory: 8M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project cloudera-impala-jdbc-example: An exception occured while executing the Java class. null: InvocationTargetException: org/apache/hadoop/conf/Configuration: org.apache.hadoop.conf.Configuration -> [Help 1]

**Comment by Seraphim-Eve** [comment]
Configuration.class can't in your $TOMCAT_HOME/work/Catalina/localhost/YOUR_WEB_APP_NAME.

**Comment by ozzy-a1** [comment]
adding a dependency to hadoop-core solved it.

**Comment by onefoursix** [comment]
Sorry about the issue; yes I was missing some deps.  I added the missing deps (there was more than one missing) and added an example run outside of maven to test the classpath directly.  I also created branches for CDH 4.7 and CDH 5.1
